name: 'Git Queue'
description: 'Job queue using git empty commits'
author: 'Jose Celano'
branding:
  icon: 'lock'
inputs:
  queue_name:
    description: 'queue name'
    required: true
  action:
    description: 'the action you want to perform'
    required: true
    options:
      - next-job
      - create-job
      - mark-job-as-done
  job_payload:
    description: 'job payload'
  git_repo_dir:
    description: 'the git repository directory. Default is the current working dir.'
    required: false
  signing_key:
    description: 'the git repository directory. Default is the current working dir.'
    required: false    
outputs:
  job_created:
    description: 'boolean, true if the job was created successfully'
  job_commit:
    description: 'the commit hash of newly created commits, when the action creates a new commit'
  job_payload:
    description: 'the job payload'
runs:
  using: 'node16'
  main: 'dist/index.js'
