name: 'Git Queue'
description: 'Job queue using git empty commits'
author: 'Jose Celano'
branding:
  icon: 'lock'
inputs:
  queue_name:
    description: 'Queue name. It can not contain special characters or white spaces'
    required: true
  action:
    description: 'The action you want to perform'
    required: true
    options:
      - next-job
      - create-job
      - mark-job-as-done
  job_payload:
    description: 'Job payload. It can be any string'
  git_repo_dir:
    description: 'The git repository directory. The default value is the current working dir'
    required: false
  git_commit_author:
    description: 'The git commit --author argument: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---authorltauthorgt'
    required: false
  git_commit_signing_key:
    description: 'The git commit --gpg-sign argument: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---gpg-signltkeyidgt'
    required: false
  git_commit_no_gpg_sign:
    description: 'The git commit --no-gpg-sign argument: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-gpg-sign'
    required: false    
outputs:
  job_created:
    description: 'Boolean, true if the job was created successfully'
  job_commit:
    description: 'The commit hash of the newly created commits, when the action creates a new commit'
  job_payload:
    description: 'The job payload'
runs:
  using: 'node16'
  main: 'dist/index.js'
