name: Test git-queue action

on:
  push:
    branches: [main, issue-*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Show default runner node version
        run: node --version

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
          fingerprint: 'BD98B3F42545FF93EFF55F7F3F39AA1432CA6AD7'

      - name: Install dependencies and build
        run: |
          cd ./.github/actions/git-queue
          yarn install && yarn build

      - name: Test
        run: |
          cd ./.github/actions/git-queue
          yarn test

      - name: Create job
        id: create-job
        uses: ./.github/actions/git-queue
        with:
          queue_name: "Library Update [library-aaa]"
          action: "create-job"
          job_payload: '{"field": "value", "state": "pending"}'

      - name: Push create-job message
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        run: git push
     
      - name: Mutual exclusion code
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        run: echo "Running the job that requires mutual exclusion"

      - name: Get next job
        id: get-next-job
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./.github/actions/git-queue
        with:
          queue_name: "Library Update [library-aaa]"
          action: "next-job"

      - name: Mark job as done
        id: mark-job-as-done
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        uses: ./.github/actions/git-queue
        with:
          queue_name: "Library Update [library-aaa]"
          action: "mark-job-as-done"
          job_payload: '{"field": "value", "state": "done"}'

      - name: Push mark-job-as-done message
        if: ${{ steps.create-job.outputs.job_created == 'true' }}
        run: git push

      - name: Show new commits
        if: ${{ steps.mark-job-as-done.outputs.job_created == 'true' }}
        run: |
          git show --show-signature ${{ steps.create-job.outputs.job_commit }}
          git show --show-signature ${{ steps.mark-job-as-done.outputs.job_commit }}

       
