name: Update library aaa w1

# This ensures that only a single workflow of this type will run at a time
concurrency: update-library-aaa-w1

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  claim-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'      

      - name: Claim lock
        shell: bash
        run: |
          ./scripts/check-lock.sh
          git commit --allow-empty -m "claim lock ${{ github.run_id }}"
          git push

  update:
    needs: claim-lock
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars
        shell: bash
        run: |
          echo -e "GITHUB_REPOSITORY: $GITHUB_REPOSITORY\n"
          echo -e "GITHUB_WORKSPACE: $GITHUB_WORKSPACE\n"
          echo -e "GITHUB_SHA: $GITHUB_SHA\n"
          echo -e "GITHUB_REF: $GITHUB_REF\n"
          echo -e "GITHUB_HEAD_REF: $GITHUB_HEAD_REF\n"
          echo -e "GITHUB_BASE_REF: $GITHUB_BASE_REF\n"
          echo -e "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME\n"
          echo -e "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH\n"
          echo -e "GITHUB_RUN_ID: $GITHUB_RUN_ID\n"
          echo -e "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER\n"

      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Update submodule libraries/aaa
        id: update-library
        run: |
          git submodule status libraries/aaa
          echo "::set-output name=previous_ref::$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')"
          git submodule update --remote libraries/aaa
          echo "::set-output name=current_ref::$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')"

      - name: Setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Rebase lock
        run: |
          git pull --rebase

      - name: Commit submodule update
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        run: |
          NOW=$(date)
          echo "Version ${{ steps.update-library.outputs.current_ref }} updated on $NOW" > library-aaa.version
          git add library-aaa.version
          git add libraries/aaa
          git commit -m "update library aaa to commit ${{ steps.update-library.outputs.current_ref }}"

      - name: Sync files from library
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        id: copy-library
        run: |
          rsync -a --delete --include='*.txt' ./libraries/aaa/ ./libraries_mirror/aaa

      - name: Commit all changes with a single commit
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        run: |
          git add libraries_mirror/aaa && git commit -m "library aaa synced to commit ${{ steps.update-library.outputs.current_ref }}"

      - name: Push changes
        if: ${{ steps.update-library.outputs.previous_ref != steps.update-library.outputs.current_ref }}
        run: |
          git push

  release-lock:
    if: always()
    needs: [claim-lock, update]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Rebase to pull the claim lock
        run: |
          git pull --rebase

      - name: Release lock
        run: |
          git commit --allow-empty -m "release lock ${{ github.run_id }}"
          git push
