name: Update library aaa

on:
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Debug env vars
        shell: bash
        run: |
          echo -e "GITHUB_REPOSITORY: $GITHUB_REPOSITORY\n"
          echo -e "GITHUB_WORKSPACE: $GITHUB_WORKSPACE\n"
          echo -e "GITHUB_SHA: $GITHUB_SHA\n"
          echo -e "GITHUB_REF: $GITHUB_REF\n"
          echo -e "GITHUB_HEAD_REF: $GITHUB_HEAD_REF\n"
          echo -e "GITHUB_BASE_REF: $GITHUB_BASE_REF\n"
          echo -e "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME\n"
          echo -e "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH\n"
          echo -e "GITHUB_RUN_ID: $GITHUB_RUN_ID\n"
          echo -e "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER\n"

      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Update submodule
        id: update-submodule
        shell: bash
        run: |
          git submodule status libraries/aaa
          PREVIOUS_REF=$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')
          echo "::set-output name=previous_ref::$PREVIOUS_REF"
          git submodule update --remote libraries/aaa
          CURRENT_REF=$(git submodule status | awk '{print $1}' | sed 's/-//' | sed 's/+//' | sed 's/U//')
          echo "::set-output name=current_ref::$CURRENT_REF"
          UPDATED=$(if [ "$PREVIOUS_REF" != "$CURRENT_REF" ]; then echo "true"; else echo "false"; fi)
          echo "::set-output name=updated::$UPDATED"

      - name: Debug step outputs
        run: |
          echo -e "previous_ref: ${{ steps.update-submodule.outputs.previous_ref }}"
          echo -e "current_ref: ${{ steps.update-submodule.outputs.current_ref }}"
          echo -e "updated: ${{ steps.update-submodule.outputs.updated }}"

      - name: Set git config user to GitHub Bot
        if: ${{ steps.update-submodule.outputs.updated == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git config user.signingkey '4AEE18F83AFDEB23'

      - name: Claim lock
        id: claim-lock
        if: ${{ steps.update-submodule.outputs.updated == 'true' }}
        shell: bash
        run: |
          ./scripts/check-lock.sh
          git commit -S --allow-empty -m "lock: claim ${{ github.run_id }}"
          git push
          echo "::set-output name=lock_claimed::true"

      - name: Commit submodule update
        id: commit-submodule-update
        if: ${{ steps.update-submodule.outputs.updated == 'true' && steps.claim-lock.outputs.lock_claimed == 'true' }}
        run: |
          # rebase lock
          git pull --rebase
          # commit submodule update
          git add libraries/aaa
          git commit -S -m "update library aaa to commit ${{ steps.update-submodule.outputs.current_ref }}"

      - name: Sync files from library
        if: ${{ steps.update-submodule.outputs.updated == 'true' && steps.claim-lock.outputs.lock_claimed == 'true' }}
        id: copy-library
        run: |
          rsync -a --delete --include="*/" --include="*.txt" --exclude="*" ./libraries/aaa/data/ ./libraries_mirror/aaa

      - name: Apply changes with a single commit
        if: ${{ steps.update-submodule.outputs.updated == 'true' && steps.claim-lock.outputs.lock_claimed == 'true' }}
        run: |
          git add libraries_mirror/aaa
          # commit only if there are changes
          git diff-index --quiet HEAD || git commit -S -m "library aaa synced to commit ${{ steps.update-submodule.outputs.current_ref }}"
          git push

      - name: Release lock
        if: ${{ steps.claim-lock.outputs.lock_claimed == 'true' }}
        run: |
          git pull --rebase
          git commit -S --allow-empty -m "lock: release ${{ github.run_id }}"
          git push          
