name: Worker

on:
  push:
    branches: [main]
  schedule:
    - cron: "0,10,20,30,40,50 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: issue-5-improve-claiming-lock-workflow
          fetch-depth: 0
          submodules: "true"

      - name: Get active lock
        id: get-active-lock
        shell: bash
        run: |
          ./scripts/get-active-lock.sh

      - name: Debug step outputs
        run: |
          echo "previous_ref: ${{ steps.get-active-lock.outputs.previous_ref }}"
          echo "current_ref: ${{ steps.get-active-lock.outputs.current_ref }}"
          echo "active_lock: ${{ steps.get-active-lock.outputs.active_lock }}"

      - name: Set git config user to GitHub Bot
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'   

      - name: Update submodule and commit
        id: update-submodule
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        shell: bash
        run: |
          cd libraries/aaa
          git fetch --all
          git checkout ${{ steps.get-active-lock.outputs.current_ref }}

      - name: Commit submodule update
        id: commit-submodule-update
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        shell: bash
        run: |
          git add libraries/aaa
          git commit -m "update library aaa to commit ${{ steps.get-active-lock.outputs.current_ref }}"          

      - name: Sync files from library
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        id: copy-library
        run: |
          rsync -a --delete --include="*/" --include="*.txt" --exclude="*" ./libraries/aaa/data/ ./libraries_mirror/aaa

      - name: Apply changes with a single commit
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        run: |
          git add libraries_mirror/aaa
          # commit only if there are changes
          git diff-index --quiet HEAD || git commit -m "library aaa synced to commit ${{ steps.get-active-lock.outputs.current_ref }}"
          git push

      - name: Release lock
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        run: |
          COMMIT_MESSAGE="RELEASE LOCK: JOB DONE: Library Update [library-aaa]
          \n
          Successfully completed Library Update according to specification in Lock:
          https://github.com/josecelano/library-aaa/commit/${{ steps.get-active-lock.outputs.current_ref }}"
          git commit --allow-empty -m "$(echo -e "$COMMIT_MESSAGE")"

      - name: Atomically merge changes and release lock
        if: ${{ steps.get-active-lock.outputs.active_lock == 'true' }}
        run: |
          git push
